### ISSUE TITLE
No Such File or Directory on node_modules\selenium-standalone\.selenium\chromiumedgedriver\latest-x64\msedgedriver

### ISSUE THREAD

**Issue by Avinash9969** [webdriverio/selenium-standalone#618] opened 2022-02-14 08:37 UTC
## Expected Behavior
The Execution should work as usual

## Current Behavior

Execution fails with Error

`2022-02-14T08:28:25.512Z INFO @wdio/cli:launcher: Run onPrepare hook
wdio.conf.js onPrepare starting here 7112 15504

Error in "chmod".
See more details below:
ENOENT: no such file or directory, chmod 'C:\My POCs\regression-test-suite\node_modules\selenium-standalone\.selenium\chromiumedgedriver\latest-x64\msedgedriver'
2022-02-14T08:28:55.561Z ERROR @wdio/selenium-standalone-service: Error: ENOENT: no such file or directory, chmod 'C:\My POCs\regression-test-suite\node_modules\selenium-standalone\.selenium\chromiumedgedriver\latest-x64\msedgedriver'`

## Steps to Reproduce
Package.json Dependencies
`  "dependencies": {
    "@babel/cli": "7.12.1",
    "@babel/core": "7.12.3",
    "@babel/plugin-proposal-export-default-from": "7.12.1",
    "@babel/preset-env": "7.12.1",
    "@babel/register": "7.12.1",
    "@g4/moment-utc": "3.1.7",
    "@g4/prova": "1.0.0",
    "@wdio/allure-reporter": "6.8.1",
    "@wdio/cli": "7.16.13",
    "@wdio/config": "7.16.13",
    "@wdio/cucumber-framework": "7.16.13",
    "@wdio/devtools-service": "7.16.13",
    "@wdio/local-runner": "7.16.13",
    "@wdio/selenium-standalone-service": "6.10.0",
    "@wdio/spec-reporter": "7.16.13",
    "@wdio/sync": "7.16.13",
    "allure-commandline": "2.13.0",
    "axe-core": "4.0.1",
    "chai": "4.2.0",
    "chai-sorted": "0.2.0",
    "eslint": "6.8.0",
    "eslint-config-airbnb-base": "14.2.1",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-wdio": "6.6.0",
    "faker": "4.1.0",
    "fibers": "4.0.3",
    "gherkin": "9.0.0",
    "got": "11.8.0",
    "iedriver": "3.14.2",
    "msedgedriver": "91.0.0",
    "multiple-cucumber-html-reporter": "1.18.0",
    "wdio-cucumberjs-json-reporter": "2.0.1",
    "wdio-edgedriver-service": "1.2.0",
    "wdio-iedriver-service": "0.1.0",
    "webdriverio": "6.9.0"
  }`

wdio.conf.js
`services: ['selenium-standalone']`

browser-config
`module.exports = {
	chrome: [{
		browserName: 'chrome',
		maxInstances:3,
		 acceptInsecureCerts: true,
	 'goog:chromeOptions': {
        args: ['--ignore-certificate-errors']
      },

    path: '/wd/hub'
	}],
	firefox: [{
		browserName: 'firefox',
		maxInstances: 5

	}],
	safari: [{
		browserName: 'safari',
		maxInstances: 5
	}],
	ie: [{
        browserName: 'internet explorer'
    }],
    edge: [{
        browserName: 'MicrosoftEdge',
        maxInstances: 1 // must be 1 for EdgeHtml, can be more for ChromiumEdge.
    }],
	phantomjs: [{
		browserName: 'phantomjs',
		platform: '',
		version: '',
		maxInstances: 5
	}],
	chromeFirefox: [{
		browserName: 'chrome',
		maxInstances: 5
	}, {
		browserName: 'firefox',
		maxInstances: 5
	}],
	chromeFirefoxSafari: [{
		browserName: 'chrome',
		maxInstances: 5
	}, {
		browserName: 'firefox',
		maxInstances: 5
	}, {
		browserName: 'safari',
		maxInstances: 5
	}],
	remoteFirefox: [{
        browserName: 'firefox',
        port: 4444
    }]
};
`

1.  Command to run -->npm run wdio wdio.conf.js

## Logs
`2022-02-14T08:28:25.300Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2022-02-14T08:28:25.512Z INFO @wdio/cli:launcher: Run onPrepare hook
wdio.conf.js onPrepare starting here 7112 15504

Error in "chmod".
See more details below:
ENOENT: no such file or directory, chmod 'C:\My POCs\regression-test-suite\node_modules\selenium-standalone\.selenium\chromiumedgedriver\latest-x64\msedgedriver'
2022-02-14T08:28:55.561Z ERROR @wdio/selenium-standalone-service: Error: ENOENT: no such file or directory, chmod 'C:\My POCs\regression-test-suite\node_modules\selenium-standalone\.selenium\chromiumedgedriver\latest-x64\msedgedriver'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prova-test-suite@0.0.1 test: `wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prova-test-suite@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\P10\AppData\Roaming\npm-cache\_logs\2022-02-14T08_28_55_598Z-debug.log `

## Your Environment
* Version of `selenium-standalone` that you are using: 8.0.9
* Is there another tool calling `selenium-standalone` on your behalf:
* System/platform:
* Other details that might be important:

**Comment by christian-bromann** [comment] 2022-02-14 09:21
@Avinash9969 can you provide the complete logs? It seems that something went wrong downloading the file given it isn't found.

**Comment by christian-bromann** [comment] 2022-02-14 10:39
Seems to be a duplicate of webdriverio/webdriverio#8006

**Closed by christian-bromann** 2022-02-14 10:39 UTC
