### ISSUE TITLE
v7 unable to download chromedriver versions >114 

### ISSUE THREAD

**Issue by gpaciga** [webdriverio/selenium-standalone#825] opened 2023-08-16 15:23 UTC
With the @wdio/selenium-standalone v7.31.1, installing chromedriver results in version 114 being downloaded even though the most recent version is 116. This seems to have been triggered with the Chrome v116 was released. This is presumably related to the Chrome For Testing changes.

Support for this was added in #817, but WDIO v7 is supposed to be LTS until October 2023, so it would be nice to see this backported, given that an upgrade to WDIO 8 for us is not trivial and may take some weeks.

## Logs

```
11:17 $ npx selenium-standalone install --singleDriverInstall=chrome
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar
to: /Users/gpaciga/git/automation-testing/donna-automation-e2e/node_modules/selenium-standalone/.selenium/selenium-server/4.4.0/selenium-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64.zip
to: /Users/gpaciga/git/automation-testing/donna-automation-e2e/node_modules/selenium-standalone/.selenium/chromedriver/latest-x64/chromedriver

[==                  ] 9%      https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64.zip---
File from https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar has already been downloaded
[====================] 100%      https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64.zip

-----
selenium-standalone installation finished
-----
```

Note the downloaded version here is 114.0.5735.90, but (at time of writing) should be 116.0.5845.96

**Comment by christian-bromann** [comment] 2023-08-16 15:40
Thanks for reporting!

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by udarrr** [comment] 2023-08-19 16:48
Hello @gpaciga  I think it's because in your npx cache exists old version selenium-standalone. Better clean up it. 
Because the option works properly.

![image](https://github.com/webdriverio/selenium-standalone/assets/77188735/578d73b9-59fc-4684-946f-9b6d3d08af05)

**Comment by RangaPavan225** [comment] 2023-08-20 13:58
Hi @udarrr , I think the issue is due to the changes in the process of downloading the chrome-driver through selenium-standalone. 
> If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading.

For reference: https://chromedriver.chromium.org/downloads

**Comment by udarrr** [comment] 2023-08-21 08:19
I don't think so, what you are mentioned already has been fixed. The issue regarding npx

**Comment by RangaPavan225** [comment] 2023-08-21 12:23
> Hi @RangaPavan225 I don't think so, what you are mentioned already has been fixed. The issue regarding npx

Thanks @udarrr for the reply. I've upgraded my selenium standalone server to latest. But unable to use several functions like maximizeWindow, minimizeWindow from browser but were working with the previous version and old chrome version. Any issues from this part?

**Comment by christian-bromann** [comment] 2023-08-21 14:55
@RangaPavan225 this sounds like you don't have a driver running and WebdriverIOs defaulted back to use the devtools package for automation. Ensure that your session connects to a browser driver.

**Comment by gpaciga** [comment] 2023-08-21 15:12
@udarr It is true that `selenium-standalone@9` will see more recent versions of chrome. But `@wdio/selenium-standalone-service` 7.31.1 has its dependency as `"selenium-standalone": "^8.0.3"`, so right now it uses `selenium-standalone` 8.3, which still only downloads up to chrome 114.

**Comment by christian-bromann** [comment] 2023-08-21 15:15
@gpaciga mind raising a PR to the `v7` branch in the WebdriverIO repository with an update?

**Comment by christian-bromann** [comment] 2023-08-21 15:21
Yes, a version change should be fine

**Comment by dlIntra** [comment] 2023-08-21 15:23
Using selenium-standalone@7 I am experiencing the same as the original post. The latest in the npm registry for 7.x is 7.1.0. Will this CLI receive the patch?

**Comment by gpaciga** [comment] 2023-08-21 15:41
@christian-bromann  looks like dependabot already did: https://github.com/webdriverio/webdriverio/pull/10943 but it hasn't been released yet

**Comment by christian-bromann** [comment] 2023-08-21 15:43
I can trigger a release then.

**Comment by christian-bromann** [comment] 2023-08-21 16:58
Merged the fix.

**Closed by christian-bromann** 2023-08-21 16:58 UTC
Labels: help wanted, Bug 🐛

**Comment by isc-aray** [comment] 2023-08-22 18:37
Unfortunately Selenium-Standalone@9 requires Node 16, which makes it incompatible with WebdriverIO 7 sync. Any chance we could get this backported to Selenium-Standalone@8?

**Comment by christian-bromann** [comment] 2023-08-22 19:01
> Node 16, which makes it incompatible with WebdriverIO 7 sync

You can use Node.js v16 with WebdriverIO v7

**Comment by isc-aray** [comment] 2023-08-22 19:07
> You can use Node.js v16 with WebdriverIO v7

Yes, but not with @wdio/sync, per https://github.com/webdriverio/webdriverio/issues/7704.

**Comment by christian-bromann** [comment] 2023-08-22 19:10
You are right. Unfortunately we had to bump the Node.js version as Chrome for Testing requires Node.js v16.3.0. At this point I only can urge to update your WebdriverIO setup and migrate to async. There is a [migration guide](https://webdriver.io/docs/async-migration) in the docs.

**Comment by dlIntra** [comment] 2023-08-22 20:18
> Using selenium-standalone@7 I am experiencing the same as the original post. The latest in the npm registry for 7.x is 7.1.0. Will this CLI receive the patch?

Is the v7 selenium-standalone CLI (popular globally installed package -- not @wdio/selenium-standalone-service) going to have continued support for this?

**Comment by christian-bromann** [comment] 2023-08-22 21:28
> have continued support for this?

What do you mean by `this`?

**Comment by RangaPavan225** [comment] 2023-08-23 08:20
> @RangaPavan225 this sounds like you don't have a driver running and WebdriverIOs defaulted back to use the devtools package for automation. Ensure that your session connects to a browser driver.

Hi @christian-bromann, starting a selenium standalone server manually resolved the issue. But how do I make it automatic run everytime as a prerequisite when I try to run a wdio testcase in jenkins and also in local?

**Comment by RangaPavan225** [comment] 2023-08-23 15:09
> > But how do I make it automatic run everytime as a prerequisite when I try to run a wdio testcase in jenkins and also in local?
> 
> You can use the `@wdio/selenium-standalone-service` to start this automatically as part of the WebdriverIO testrunner.
> 
> > npm i -g selenium-standalone@7
> 
> @dlIntra you will have to use the latest version of this package which is v9.x

<img width="427" alt="image" src="https://github.com/webdriverio/selenium-standalone/assets/98270054/df9474ef-19fc-41b9-919c-1c1c31b1ff5f">

I'm already using the service but still it's not working, any mistakes I made here please?

**Comment by dlIntra** [comment] 2023-08-23 15:27
> > npm i -g selenium-standalone@7
> 
> @dlIntra you will have to use the latest version of this package which is v9.x

I did try retrofitting with the solution I found in the code changes to use the chrome-for-testing baseURL
`selenium-standalone install --drivers.chrome.baseURL=https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing --drivers.chrome.version=116.0.5845.96`
Doesn't locate the driver because the CLI doesnt compile the final URL correctly... but is this possible? If so please advise.

**Comment by christian-bromann** [comment] 2023-08-23 15:31
> I'm already using the service but still it's not working, any mistakes I made here please?

Please update your package version to `@wdio/selenium-standalone-service@8.15.0`

**Comment by RangaPavan225** [comment] 2023-08-24 07:56
> > I'm already using the service but still it's not working, any mistakes I made here please?
> 
> Please update your package version to `@wdio/selenium-standalone-service@8.15.0`

I've updated to the specified version, but I'm using node14 to run my testcases. Will that be a reason why the server is not starting by itself?
Also I cannot use node16 since there is an issue with fibers on node16. Let me know what to do please

**Comment by christian-bromann** [comment] 2023-08-24 14:42
Unfortunately Chrome for Testing requires Node.js v16. I really recommend at this point to upgrade to the latest LTS Node.js version and WebdriverIO.

**Comment by MikeBaxter-Canopy** [comment] 2023-08-24 15:09
This has been a breaking change for me too. I had been running @wdio/sync with fibers, using node 14 like @RangaPavan225. 

My understanding has been that, to be able to get chromeDriver for chrome 116, I needed to switch to node 16.

To fix this I have:
- Removed @wdio/sync from my package.json
- Uninstalled node and installed node 16.16.0
- Changed webdriverio to 7.31.1 in my package.json
- Run `npm install`
- Run `npm install selenium-standalone@latest -g` (as it would not auto update from an npm install)
- Run `selenium-standalone install`
- Run `npm install` again for good measure

Without @wdio/sync, a number of the selectors I had previously used [i.e. $(...).$(...) or $(...).parentElement() ] have stopped working:
`Property '$' does not exist on type 'JQuery<HTMLElement>'.`
`Property 'parentElement' does not exist on type 'JQuery<HTMLElement>'`

Is there some other module I need to add to replace wdio/sync?

**Comment by christian-bromann** [comment] 2023-08-24 18:39
> Is there some other module I need to add to replace wdio/sync?

No, make sure you have your TypeScript set up correctly according to the [docs](https://webdriver.io/docs/typescript). I recommend switching to the latest version of WebdriverIO.

**Comment by RangaPavan225** [comment] 2023-08-31 11:02
@christian-bromann , I'm trying the same with Firefox browser but it's not working, below is the error:

> org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: Argument --remote-debugging-port can't be set via capabilities

I'm using below statements in wdio.conf.firefox file:

> services: [
        ['selenium-standalone', { drivers: { firefox: '0.30.0' } }]
    ],

> capabilities: [{
        maxInstances: 5,
        browserName: 'firefox'
    }],

Please let me know how to resolve this issue, btw I'm using latest selenium-standalone server

**Comment by christian-bromann** [comment] 2023-08-31 15:46
> firefox: '0.30.0'

I recommend testing on the latest Geckodriver version which is `v0.33.0`. I don't know what causes the error. Updating WebdriverIO to latest v8 is likely gonna resolve this since it will handle driver management for you.
