### ISSUE TITLE
Chromedriver v115+ unsupported downloads

### ISSUE THREAD

**Issue by JoshCrozier** [webdriverio/selenium-standalone#810] opened 2023-07-24 20:03 UTC
## Expected Behavior
The ability to run `selenium-standalone` against version of Chromedriver v115+.

There were recently updates here from the official source: https://chromedriver.chromium.org/downloads

> - If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading.
> 
> - For older versions of Chrome, please see below for the version of ChromeDriver that supports it.

## Current Behavior

Currently, only versions prior to v115 are supported.

When computing the download URL, `/LATEST_RELEASE` is appended (which is utilized for the previous download URL)
https://github.com/webdriverio/selenium-standalone/blob/9fdcf449511769f42fee5bc64cf28cad058f2e69/lib/compute-download-urls.js#L54

Conditional logic needs to be added to look at the newly released API for v115+ and higher: https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json

> For versions 115 and newer
> Starting with M115 the ChromeDriver release process is integrated with that of Chrome. The latest Chrome + ChromeDriver releases per release channel (Stable, Beta, Dev, Canary) are available at[ the Chrome for Testing (CfT) availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). As a result, you might no longer have a need for version selection — you could choose any available CfT version and simply download the correspondingly-versioned ChromeDriver binary.
> 
> For automated version downloading one can use the convenient [CfT JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json).
> 
> If you still have a need for version selection (e.g. to match a non-CfT Chrome binary with a compatible ChromeDriver binary), you might be interested in the latest-patch-versions-per-build [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json).

**Comment by christian-bromann** [comment] 2023-07-24 20:29
@JoshCrozier thanks for raising the issue. We are in the process of deprecating this project as it is no longer useful for the WebdriverIO project due to this effort: https://github.com/webdriverio/webdriverio/pull/10767. We hope to be able to ship it by the end of this week. If you are using this package without WebdriverIO, I recommend to switch to an alternative package that allows you to use Chromedriver, e.g. [this one](https://www.npmjs.com/package/@puppeteer/browsers). If you can provide a patch that resolves the problem we are committed to merge and release it.

**Comment by tehhowch** [comment] 2023-07-24 22:17
@christian-bromann is that effort, wherein WebdriverIO will manage the drivers, being made for all officially supported versions of WebdriverIO, i.e. both [7 and 8](https://webdriver.io/versions)? Or will consumers that use v7 and selenium-standalone be forced to abandon testing against valid Chrome versions despite being within the LTS support window?

**Comment by christian-bromann** [comment] 2023-07-24 22:22
These changes will not be back ported to WebdriverIO v7, at least I am not planning to do it myself as I don't have the resources for it. I am happy to merge any contributions that come up with a fix for this.

That said, I can only urge to update to WebdriverIO v8. There is no reason for someone to stay on v7 and we have done all possible things to make the transition as easy as updating the version number. If someone has complications upgrading to v8 should raise an issue and we can work this out.

**Comment by Jasonizl** [comment] 2023-07-25 08:09
As in opening a issue, do you mean in this project or in the webdriverIO project  @christian-bromann?
Me and my team are also struggling to update from v7 to v8 because of breaking changes with how scrolling works for example.

**Comment by christian-bromann** [comment] 2023-07-25 15:48
> As in opening a issue

Yes, ideally with a reproducible example.

**Comment by udarrr** [comment] 2023-08-05 15:14
https://github.com/webdriverio/selenium-standalone/pull/814

**Comment by christian-bromann** [comment] 2023-08-08 18:50
Thanks @udarrr for all your work. Released as `v9.0.0`.

**Closed by christian-bromann** 2023-08-08 18:50 UTC
