### ISSUE TITLE
[Bug]: Error in "getDownloadStream". Could not download zip file | M1 MacBooks

### ISSUE THREAD

**Issue by yuriibazhan** [webdriverio/selenium-standalone#803] opened 2023-07-06 07:33 UTC
same issue as here  - https://github.com/webdriverio/selenium-standalone/issues/709

 404 https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64_m1.zip

**Comment by christian-bromann** [comment] 2023-07-06 16:26
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment] 2023-07-06 16:28
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment] 2023-07-24 20:30
Duplicate of #725

**Closed by christian-bromann** 2023-07-24 20:30 UTC
